### ISSUE TITLE
3.1.0 release was a breaking change

### ISSUE THREAD

**Issue by yoitsro** [bojand/grpc-create-metadata#2]
Since 3.1.0 now relies on `@grpc/grpc-js`, the packages which still rely on `grpc` aren't working.

Specifically, what's happening is that the instances of `Metadata` returned from here are now the `grpc-js` versions. [Within the `grpc` package](https://github.com/grpc/grpc-node/blob/grpc%401.25.x/packages/grpc-native-core/src/client.js#L527), an `instanceof` check is done comparing the metadata object passed in against the Metadata type within the `grpc` package, which will never pass, causing failures.

**Comment by bojand** [comment]
Ugh yes that's not good, that was an oversight... I'll deprecate this version and publish 4.0.0 in a little bit when I can.

**Comment by yoitsro** [comment]
Much appreciated! Give me a shout if I can help.

**Comment by bojand** [comment]
[3.1.0 has been deprecated](https://www.npmjs.com/package/grpc-create-metadata/v/3.1.0).
For old behaviour please continue using 3.0.0. For new package with `@grpc/grpc-js` use 4.0.0.
